---
driver:
  name: docker
  use_sudo: false
  provision_command: 
    - mkdir -p /run/sshd

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[box::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
