" box chef system wide vim configuration

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Vim5 and later versions support syntax highlighting. Uncommenting the
" following enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

filetype plugin indent on

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

" set indents to 2 spaces by default
set expandtab
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

" use english for spellcheck
set spelllang=en
set spell

set mousemodel=popup

